---
#-----initialize the docker swarm-----
- name: Setting up Swarm
  block:
    - name: Initiating the swarm with default parameters
      shell: docker swarm init
      ignore_errors: True
      register: init_swarm

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token

    - name: Show Worker Token
      debug: var=worker_token.stdout

    - name: Master Token
      command: docker swarm join-token manager -q
      register: master_token

    - name: Show Master Token
      debug: var=master_token.stdout

    - name: "set fact: join token worker"
      set_fact:
        join_token_worker: "{{ worker_token.stdout }}"

    - name: "set fact: join token manager"
      set_fact:
        join_token_manager: "{{ master_token.stdout }}"
